#!/usr/bin/env node
// Generated mỗi build: ghi public/version.json + src/build-version.ts với
// cùng 1 version string (ms epoch). Client poll /version.json để phát hiện
// deploy mới và bắt buộc reload.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, '..');

const version = Date.now().toString();
const builtAt = new Date().toISOString();

const json = JSON.stringify({ version, builtAt }, null, 2);
mkdirSync(resolve(root, 'public'), { recursive: true });
writeFileSync(resolve(root, 'public', 'version.json'), json + '\n');

const tsSrc =
  '// Auto-generated by scripts/gen-version.js — do not edit by hand.\n' +
  `export const BUILD_VERSION = '${version}';\n` +
  `export const BUILD_AT = '${builtAt}';\n`;
writeFileSync(resolve(root, 'src', 'build-version.ts'), tsSrc);

console.log(`[gen-version] BUILD_VERSION=${version}  builtAt=${builtAt}`);
