// words.dart — Wordle word lists for Super Gate (5, 6, 7 letters)

// ─────────────────────────────────────────────
// 5-LETTER WORDS
// ─────────────────────────────────────────────

const List<String> targetWords5 = [
  'about', 'above', 'abuse', 'actor', 'acute',
  'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album',
  'alert', 'alike', 'alive', 'alley', 'allow',
  'alone', 'along', 'alter', 'angel', 'anger',
  'angle', 'angry', 'apart', 'apple', 'apply',
  'apron', 'argue', 'arise', 'armor', 'aroma',
  'aside', 'asset', 'atlas', 'attic', 'audio',
  'audit', 'avoid', 'awake', 'award', 'aware',
  'badly', 'baker', 'basic', 'basis', 'beach',
  'beard', 'beast', 'began', 'begin', 'being',
  'below', 'bench', 'black', 'blade', 'blame',
  'bland', 'blank', 'blast', 'blaze', 'bleed',
  'bless', 'blind', 'block', 'blood', 'bloom',
  'blown', 'blues', 'blunt', 'board', 'bonus',
  'boost', 'booth', 'bound', 'brain', 'brand',
  'brass', 'break', 'breed', 'brick', 'bride',
  'brief', 'bring', 'broad', 'broke', 'brook',
  'brown', 'brush', 'build', 'built', 'burst',
  'buyer', 'cable', 'cabin', 'candy', 'carry',
  'catch', 'cause', 'cease', 'chain', 'chair',
  'chaos', 'charm', 'chart', 'chase', 'cheap',
  'check', 'cheek', 'chess', 'chest', 'chief',
  'child', 'civic', 'civil', 'claim', 'clash',
  'class', 'clean', 'clear', 'clerk', 'click',
  'cliff', 'climb', 'clock', 'clone', 'close',
  'cloud', 'coach', 'coast', 'color', 'comet',
  'comic', 'coral', 'count', 'court', 'cover',
  'crack', 'craft', 'crash', 'crazy', 'cream',
  'cross', 'crowd', 'crown', 'crush', 'daily',
  'dance', 'death', 'debut', 'decay', 'delay',
  'delta', 'demon', 'depot', 'depth', 'derby',
  'digit', 'dirty', 'disco', 'diver', 'doing',
  'doubt', 'dowry', 'draft', 'drain', 'drama',
  'drank', 'dread', 'dream', 'dress', 'drift',
  'drink', 'drive', 'drove', 'drown', 'dryer',
  'dwarf', 'early', 'earth', 'eight', 'elite',
  'empty', 'enemy', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'ethic', 'event', 'every',
  'exact', 'exist', 'extra', 'fable', 'faced',
  'faith', 'false', 'fancy', 'fatal', 'feast',
  'fence', 'fever', 'fiber', 'field', 'fifth',
  'fifty', 'fight', 'final', 'first', 'fixed',
  'flame', 'flash', 'fleet', 'flesh', 'float',
  'flood', 'floor', 'flour', 'fluid', 'flush',
  'focus', 'force', 'forge', 'forte', 'forum',
  'found', 'frame', 'frank', 'fraud', 'fresh',
  'front', 'frost', 'fruit', 'fully', 'funny',
  'giant', 'given', 'gland', 'globe', 'gloom',
  'gloss', 'glove', 'going', 'grace', 'grade',
  'grain', 'grand', 'grant', 'grape', 'grasp',
  'grass', 'grave', 'great', 'green', 'greet',
  'grief', 'grind', 'groan', 'group', 'grove',
  'grown', 'guard', 'guide', 'guild', 'guilt',
  'guise', 'gusto', 'habit', 'happy', 'harsh',
  'heart', 'heavy', 'hence', 'herbs', 'hertz',
  'hotel', 'house', 'human', 'humor', 'hurry',
  'hydro', 'ideal', 'image', 'imply', 'inbox',
  'index', 'indie', 'input', 'inter', 'intra',
  'intro', 'irony', 'issue', 'ivory', 'jewel',
  'joint', 'joker', 'judge', 'juice', 'jumbo',
  'keeps', 'knack', 'knife', 'knight', 'known',
  'label', 'large', 'laser', 'later', 'layer',
  'learn', 'lease', 'legal', 'lemon', 'level',
  'light', 'limit', 'liner', 'liver', 'local',
  'lodge', 'logic', 'loose', 'lower', 'loyal',
  'lucky', 'lunar', 'lusty', 'magic', 'major',
  'manor', 'maple', 'march', 'match', 'mayor',
  'media', 'mercy', 'merge', 'metal', 'might',
  'minor', 'minus', 'model', 'money', 'month',
  'moral', 'motor', 'motto', 'mount', 'mouth',
  'music', 'naive', 'nerve', 'never', 'night',
  'noble', 'noise', 'north', 'noted', 'novel',
  'nurse', 'nylon', 'occur', 'ocean', 'offer',
  'often', 'olive', 'onset', 'orbit', 'order',
  'other', 'ought', 'outer', 'owner', 'oxide',
  'ozone', 'paced', 'paint', 'panel', 'panic',
  'paper', 'party', 'pasta', 'patch', 'pause',
  'peace', 'pearl', 'penny', 'phase', 'phone',
  'photo', 'piano', 'pilot', 'pinch', 'pitch',
  'pixel', 'place', 'plain', 'plane', 'plant',
  'plate', 'plaza', 'plead', 'pluck', 'plume',
  'plunge', 'point', 'polar', 'pound', 'power',
  'press', 'price', 'pride', 'prime', 'print',
  'prior', 'prize', 'probe', 'proof', 'prose',
  'proud', 'prove', 'psalm', 'pulse', 'punch',
  'queen', 'query', 'quest', 'queue', 'quick',
  'quiet', 'quota', 'quote', 'radar', 'radio',
  'raise', 'rally', 'range', 'rapid', 'ratio',
  'reach', 'react', 'ready', 'realm', 'rebel',
  'refer', 'relay', 'renew', 'repay', 'reply',
  'reset', 'rider', 'ridge', 'right', 'risen',
  'risky', 'rival', 'river', 'robot', 'rocky',
  'roman', 'rough', 'round', 'route', 'royal',
  'rugby', 'ruler', 'rural', 'saint', 'salad',
  'sauce', 'scale', 'scare', 'scene', 'scope',
  'score', 'scout', 'screw', 'seize', 'sense',
  'serve', 'seven', 'shade', 'shake', 'shame',
  'share', 'shark', 'sharp', 'sheet', 'shelf',
  'shell', 'shift', 'shine', 'shirt', 'shock',
  'shoot', 'short', 'shout', 'sight', 'sigma',
  'since', 'sixth', 'sized', 'skill', 'sleep',
  'slice', 'slide', 'slope', 'smart', 'smile',
  'smoke', 'solid', 'solve', 'sorry', 'south',
  'space', 'spare', 'spark', 'speak', 'speed',
  'spend', 'spine', 'split', 'spoke', 'spoon',
  'sport', 'spray', 'squad', 'stack', 'staff',
  'stage', 'stain', 'stake', 'stale', 'stall',
  'stand', 'stare', 'start', 'state', 'stays',
  'steal', 'steel', 'steep', 'steer', 'stern',
  'stick', 'stiff', 'still', 'stock', 'stone',
  'stood', 'storm', 'story', 'stove', 'strap',
  'straw', 'strip', 'stuck', 'study', 'style',
  'sugar', 'suite', 'super', 'surge', 'swamp',
  'swear', 'sweep', 'sweet', 'swept', 'swift',
  'sword', 'swore', 'sworn', 'table', 'taste',
  'teach', 'tense', 'tenth', 'their', 'theme',
  'there', 'thing', 'think', 'third', 'those',
  'threw', 'throw', 'thumb', 'tidal', 'tiger',
  'tight', 'timer', 'tired', 'toast', 'today',
  'token', 'topic', 'total', 'touch', 'tough',
  'tower', 'toxic', 'track', 'trade', 'trail',
  'train', 'trait', 'tramp', 'trash', 'treat',
  'trend', 'trial', 'trick', 'tried', 'troop',
  'trust', 'truth', 'tumor', 'tuner', 'twice',
  'twist', 'ultra', 'uncle', 'under', 'union',
  'unity', 'until', 'upper', 'urban', 'usage',
  'usual', 'utter', 'valid', 'value', 'video',
  'vigor', 'viral', 'virus', 'visit', 'vital',
  'voice', 'voter', 'vying', 'waste', 'watch',
  'water', 'weave', 'wedge', 'weigh', 'weird',
  'whale', 'wheat', 'wheel', 'where', 'which',
  'while', 'white', 'whole', 'whose', 'wider',
  'witch', 'woman', 'world', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrath', 'wrist',
  'wrong', 'yacht', 'yield', 'young', 'youth',
  'zebra', 'zonal',
];

// validWords5: superset (gồm cả targetWords5 + extra valid guesses)
List<String> get validWords5 => targetWords5;

// ─────────────────────────────────────────────
// 6-LETTER WORDS
// ─────────────────────────────────────────────

const List<String> targetWords6 = [
  'accept', 'access', 'action', 'active', 'actual',
  'afford', 'afraid', 'agency', 'anchor', 'animal',
  'annual', 'answer', 'appeal', 'appear', 'aspect',
  'assert', 'assign', 'attack', 'attend', 'author',
  'autumn', 'avenue', 'battle', 'beauty', 'before',
  'behind', 'belong', 'better', 'bitter', 'border',
  'bottom', 'breach', 'breath', 'bridge', 'bright',
  'broken', 'budget', 'bundle', 'button', 'buying',
  'camera', 'cancer', 'candle', 'canyon', 'carbon',
  'career', 'castle', 'casual', 'center', 'chance',
  'change', 'charge', 'choose', 'circle', 'client',
  'closed', 'coffee', 'column', 'combat', 'coming',
  'common', 'convex', 'cookie', 'copper', 'corner',
  'costly', 'couple', 'course', 'cousin', 'create',
  'credit', 'crisis', 'critic', 'custom', 'danger',
  'decade', 'define', 'degree', 'demand', 'design',
  'desire', 'detail', 'detect', 'device', 'differ',
  'direct', 'divide', 'domain', 'double', 'dragon',
  'driver', 'during', 'easily', 'editor', 'effect',
  'effort', 'employ', 'enable', 'encode', 'energy',
  'engage', 'engine', 'ensure', 'entire', 'escape',
  'estate', 'evolve', 'exceed', 'expand', 'expect',
  'export', 'fabric', 'factor', 'famine', 'famous',
  'father', 'figure', 'filter', 'finger', 'finish',
  'flight', 'flower', 'flying', 'follow', 'forest',
  'formal', 'former', 'freely', 'frozen', 'future',
  'galaxy', 'gather', 'gender', 'gentle', 'global',
  'golden', 'ground', 'guitar', 'handle', 'happen',
  'health', 'hidden', 'higher', 'highly', 'honest',
  'hunter', 'ignore', 'impact', 'import', 'income',
  'indoor', 'infant', 'inside', 'intent', 'invite',
  'island', 'issued', 'itself', 'joyful', 'jungle',
  'justify', 'kettle', 'kitten', 'ladder', 'laptop',
  'launch', 'leader', 'length', 'lesson', 'letter',
  'likely', 'listen', 'little', 'living', 'lonely',
  'losing', 'marble', 'market', 'master', 'matter',
  'memory', 'mental', 'method', 'middle', 'mirror',
  'modern', 'moment', 'monkey', 'mother', 'mostly',
  'motion', 'moving', 'muscle', 'mutual', 'myself',
  'narrow', 'nature', 'nearly', 'needle', 'neural',
  'normal', 'notice', 'object', 'obtain', 'office',
  'online', 'option', 'orange', 'origin', 'output',
  'palace', 'parent', 'parrot', 'patent', 'people',
  'period', 'permit', 'person', 'planet', 'player',
  'pocket', 'police', 'policy', 'portal', 'potato',
  'powder', 'pretty', 'prince', 'prison', 'profit',
  'proper', 'public', 'purple', 'pursue', 'rabbit',
  'racing', 'rather', 'reason', 'recent', 'record',
  'region', 'relate', 'remain', 'render', 'repair',
  'repeat', 'report', 'rescue', 'result', 'retain',
  'return', 'reveal', 'reward', 'rocket', 'ruling',
  'sacred', 'safety', 'sample', 'school', 'search',
  'second', 'secret', 'select', 'series', 'settle',
  'signal', 'silver', 'simple', 'single', 'sister',
  'sketch', 'smooth', 'social', 'source', 'speech',
  'spring', 'square', 'status', 'steady', 'stream',
  'street', 'stress', 'strict', 'strike', 'strong',
  'studio', 'submit', 'sudden', 'suffer', 'summer',
  'supply', 'switch', 'symbol', 'system', 'target',
  'simple', 'talent', 'temple', 'tender', 'theory',
  'throat', 'throne', 'tighten', 'timber', 'timing',
  'travel', 'tribal', 'triple', 'troops', 'tunnel',
  'unlock', 'update', 'useful', 'valley', 'varied',
  'vendor', 'versus', 'vision', 'volume', 'wealth',
  'weekly', 'weight', 'winter', 'wonder', 'wooden',
  'worker', 'worthy', 'yellow', 'zenith',
];

List<String> get validWords6 => targetWords6;

// ─────────────────────────────────────────────
// 7-LETTER WORDS
// ─────────────────────────────────────────────

const List<String> targetWords7 = [
  'ability', 'absence', 'account', 'achieve', 'acquire',
  'address', 'advance', 'advisor', 'against', 'ancient',
  'another', 'anxiety', 'anybody', 'applied', 'archive',
  'arrange', 'arrival', 'article', 'assault', 'attempt',
  'attract', 'auditor', 'average', 'battery', 'because',
  'believe', 'between', 'boulder', 'captain', 'capture',
  'careful', 'century', 'chapter', 'charity', 'chicken',
  'classic', 'climate', 'collect', 'combine', 'comfort',
  'command', 'comment', 'compact', 'company', 'compare',
  'compete', 'complex', 'compute', 'concept', 'concern',
  'confirm', 'connect', 'contain', 'content', 'contest',
  'context', 'control', 'convert', 'council', 'counter',
  'country', 'covered', 'current', 'curtain', 'cutting',
  'develop', 'diamond', 'digital', 'discuss', 'display',
  'distant', 'disturb', 'diverse', 'dolphin', 'dynamic',
  'economy', 'element', 'emotion', 'enhance', 'enlarge',
  'ethical', 'examine', 'exclude', 'explain', 'explore',
  'express', 'extract', 'extreme', 'fantasy', 'feature',
  'federal', 'fiction', 'freedom', 'general', 'genetic',
  'genuine', 'glacier', 'glamour', 'glasses', 'gravity',
  'habitat', 'history', 'housing', 'hundred', 'husband',
  'improve', 'include', 'initial', 'instant', 'instead',
  'intense', 'involve', 'kingdom', 'landing', 'lasting',
  'lateral', 'leading', 'learned', 'library', 'measure',
  'mention', 'message', 'minimal', 'million', 'mineral',
  'mission', 'mixture', 'monitor', 'morning', 'mystery',
  'natural', 'network', 'neutral', 'nothing', 'nowhere',
  'nuclear', 'operate', 'opinion', 'outcome', 'outside',
  'overall', 'overlap', 'package', 'passion', 'pattern',
  'payment', 'perfect', 'perform', 'perhaps', 'picture',
  'pioneer', 'plastic', 'popular', 'present', 'primary',
  'process', 'product', 'program', 'project', 'promise',
  'protect', 'provide', 'purpose', 'quarter', 'quickly',
  'radical', 'rapidly', 'reading', 'rebuild', 'receive',
  'recruit', 'reflect', 'release', 'require', 'resolve',
  'restore', 'revenue', 'reverse', 'roughly', 'runtime',
  'science', 'section', 'serious', 'service', 'setting',
  'shelter', 'shortage', 'similar', 'society', 'somehow',
  'someone', 'complex', 'speaker', 'special', 'species',
  'stadium', 'staying', 'storage', 'subject', 'suggest',
  'support', 'surface', 'survive', 'suspect', 'stretch',
  'student', 'success', 'texture', 'therapy', 'through',
  'tonight', 'tornado', 'tourism', 'towards', 'trading',
  'trained', 'teacher', 'triumph', 'trouble', 'turning',
  'typical', 'uniform', 'unknown', 'unusual', 'upgrade',
  'version', 'village', 'virtual', 'visible', 'weather',
  'website', 'western', 'whether', 'winning', 'without',
  'writing', 'younger',
];

List<String> get validWords7 => targetWords7;

// ─────────────────────────────────────────────
// LEGACY ALIAS (backward compat với wordle_game.dart cũ)
// ─────────────────────────────────────────────
List<String> get targetWords => targetWords5;
List<String> get validWords => validWords5;

// Helper: lấy word list theo độ dài
List<String> getTargetWordsByLength(int len) {
  switch (len) {
    case 6:
      return targetWords6;
    case 7:
      return targetWords7;
    default:
      return targetWords5;
  }
}

List<String> getValidWordsByLength(int len) {
  switch (len) {
    case 6:
      return validWords6;
    case 7:
      return validWords7;
    default:
      return validWords5;
  }
}
